spring:
  sql.init.mode: always
  datasource:
    url: jdbc:mariadb://localhost:3306/registration
    username:
    password:

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect
      format_sql: true
      show-sql: true

  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
